# For StorageOS v2.x 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  labels:
    app: storageos
provisioner: csi.storageos.com # CSI Driver (Recommended)
parameters:
  fsType: ext4
  pool: default
  adminSecretNamespace: storageos-operator
  adminSecretName: storageos-api
