# For StorageOS v2.x only with CSI

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageos-replicated
provisioner: csi.storageos.com # CSI driver (recommended)
parameters:
  fsType: ext4
  pool: default
  storageos.com/replicas: "1" # Labels allowed only when using CSI
